### ISSUE TITLE
Metadata plan

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#54]
How I would approach the metadata issue:

Our input from the modellers looks a bit like this (it's actually a bit messier, but whatever), minus `meta.yaml` and `stories/`:

Scenario set/
  - geometry
  - meta.yaml
  - scenarios/
    - scenario1/
      - links.csv
      - zones.csv
      - od.csv
    - scenario2
      - ...
    - ...
  - stories/
    - kyiv-southern-connections.yaml
    - total-ton-comparison.yaml

I suggest metadata is written in yaml or toml rather than JSON because they're a bit easier for humans to write.

meta.yaml might contain:

```yaml
name: "Greener Connectivity in the EAP countries"
description: "whatever"
links:
   modes:
      initial:
         - Road
         - IWW
         - Air
         - Maritime
   columns:
      LType:
         name: Link type
         offset: false
      Speed_cong_road:
         name: Speed of road with congestion model
         good: smaller
      VCR:
         quantiles: [0, .3, .5, 1, 1.5, 2, 3, inf]
         good: smaller
         palette: Purples
      Length:
         use: false
zones:
   inner-zone-col: EaP
scenarios:
   scenario1:
      name: TEN-T++
      description: Upgrade strategic roads and rail beyond the TEN-T programme
```

The implicit defaults there are `offset: true`, `good: bigger`, `quantiles: auto`, `use: true`.

meta.yaml would be the first file sought by the data loading function and defines the default palette options for the viewer, human-friendly names, etc.

---

The stories.yaml are frozen views of the viewer's configuration at a point of interest, plus metadata:

total-ton-comparison.yaml

```yaml
name: Total tonnage in do nothing and TEN-T++ scenarios
description: TEN-T++ results in a more balanced distribution of freight throughout the region. Southern Ukraine benefits most strongly... blah blah
Links:
   on: true
   colourBy: V_total_tons
   weightBy: V_total_tons
   palette: YlOrRd
   offset: true
   reverse: false
Zones:
   on: false
```
